"use strict";

export {
  DIFFICULTIES,
  SKILL_ORDER,
  CASE_ORDER,
  BASE_PRACTICE,
  LANGUAGE_ORDER,
  LANGUAGE_METADATA,
  LANGUAGE_UI,
  LANGUAGE_OVERRIDES,
  STATEMENT_TRANSLATIONS
} from "../data/index.js";

